services:
  - type: web
    name: naisha-coffee
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn naisha_coffee.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
