# Generated by Django 6.0.6 on 2026-06-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji icon, e.g. ☕', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nayesa Coffee', max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_badge', models.CharField(blank=True, default='Best Coffee In Town', max_length=60)),
                ('hero_title', models.CharField(default='Best Coffee', max_length=120)),
                ('hero_subtitle', models.CharField(default='Make your day great with our special coffee!', max_length=200)),
                ('hero_description', models.TextField(default='Welcome to our coffee paradise, where every bean tells a story and every cup sparks joy.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_button_text', models.CharField(default='Order Now', max_length=40)),
                ('hero_button_link', models.CharField(default='#menu', max_length=200)),
                ('hero_secondary_button_text', models.CharField(blank=True, default='Contact Us', max_length=40)),
                ('hero_secondary_button_link', models.CharField(blank=True, default='#contact', max_length=200)),
                ('about_title', models.CharField(default='Our Story', max_length=120)),
                ('about_text', models.TextField(default='Founded with a love for great coffee, Nayesa Coffee brings you freshly roasted beans, a cozy atmosphere and baristas who treat every cup like a craft.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('years_experience', models.PositiveIntegerField(default=5)),
                ('cups_served', models.PositiveIntegerField(default=50000)),
                ('happy_customers', models.PositiveIntegerField(default=12000)),
                ('address', models.CharField(default='123 Coffee Street, Dhaka, Bangladesh', max_length=200)),
                ('phone', models.CharField(default='+880 1234 567890', max_length=40)),
                ('email', models.EmailField(default='hello@nayesacoffee.com', max_length=254)),
                ('opening_hours', models.CharField(blank=True, default='Mon - Sun: 8:00 AM - 10:00 PM', max_length=200)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL (optional)')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, default='Brewed with love, served with a smile.', max_length=250)),
                ('copyright_text', models.CharField(blank=True, default='© Nayesa Coffee. All rights reserved.', max_length=150)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(default='Barista', max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, help_text='e.g. Regular Customer', max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('is_featured', models.BooleanField(default=False, help_text="Show in 'Popular Picks'")),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coffee.menucategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
