# Generated by Django 6.0.6 on 2026-06-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Naisha Coffee Gulshan', max_length=80)),
                ('area', models.CharField(help_text='e.g. Gulshan, Dhaka', max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='branches/')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('opening_hours', models.CharField(blank=True, default='8:00 AM - 10:00 PM', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(default='Founded with a love for great coffee, Naisha Coffee brings you freshly roasted beans, a cozy atmosphere and baristas who treat every cup like a craft.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='House 12, Road 5, Gulshan, Dhaka, Bangladesh', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='© Naisha Coffee. All rights reserved.', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='hello@naishacoffee.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Naisha Coffee', max_length=60),
        ),
    ]
